#!/usr/bin/env python3
"""
Test script for GELS Localization Service.

Simulates a complete cycle message and calls the localization service handler
to verify the full pipeline works correctly.

Usage:
    # Without ROS (standalone):
    python test_localization_service.py

    # With ROS (service simulation):
    rosrun gels_localization test_localization_service.py
"""

import sys
import os
import numpy as np

# Add scripts directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import mag_dipole_model for synthetic Hall sensor data generation
from mag_dipole_model import mag_dipole_model, eul2rotm

# Mock ROS message classes for standalone testing (define BEFORE imports)
class MockPose:
    def __init__(self, x=0, y=0, z=0, qx=0, qy=0, qz=0, qw=1):
        self.position = type('obj', (object,), {'x': x, 'y': y, 'z': z})()
        self.orientation = type('obj', (object,), {'x': qx, 'y': qy, 'z': qz, 'w': qw})()

class MockSensorReading:
    def __init__(self, id=1, x=0.0, y=0.0, z=0.0):
        self.id = id
        self.x = x
        self.y = y
        self.z = z

class MockSlotData:
    def __init__(self, slot=0, sensor_data=None, pose=None):
        self.slot = slot
        self.sensor_data = sensor_data or []
        self.pose = pose or MockPose()

class MockLocalizationResponse:
    """Mock response for LocalizeCycle service when ROS is not available."""
    def __init__(self):
        self.success = False
        self.localization_pose = MockPose()
        self.position_error = 0.0
        self.orientation_error = 0.0

class MockLocalizeCycleRequest:
    def __init__(self, cycle_id=1, mode='CCI', sensor_ids=None, slot_data=None, ground_truth_pose=None):
        self.cycle_id = cycle_id
        self.mode = mode
        self.num_slots = len(slot_data) if slot_data else 0
        self.sensor_ids = sensor_ids or [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        self.slot_data = slot_data or []
        self.ground_truth_pose = ground_truth_pose or MockPose()


# Import the handler function directly for standalone testing
import localization_service_node
from localization_service_node import (
    process_hall_data,
    build_D_cal,
    quaternion_z_axis,
    load_configuration,
    handle_localize_cycle,
    R_CORR,
    D_LIST,
    GS_TO_TESLA,
    LocalizeCycleResponse,
)

# Patch LocalizeCycleResponse if ROS is not available
if LocalizeCycleResponse is None:
    localization_service_node.LocalizeCycleResponse = MockLocalizationResponse


def quaternion_to_rotation_matrix(q):
    """
    Convert quaternion [w, x, y, z] to rotation matrix.

    Args:
        q: quaternion [w, x, y, z]

    Returns:
        np.ndarray: 3x3 rotation matrix
    """
    w, x, y, z = q[0], q[1], q[2], q[3]
    return np.array([
        [1 - 2*(y*y + z*z), 2*(x*y - z*w), 2*(x*z + y*w)],
        [2*(x*y + z*w), 1 - 2*(x*x + z*z), 2*(y*z - x*w)],
        [2*(x*z - y*w), 2*(y*z + x*w), 1 - 2*(x*x + y*y)]
    ])


def quaternion_z_axis(q):
    """
    Extract the z-axis direction from a quaternion.

    Args:
        q: quaternion [w, x, y, z]

    Returns:
        np.ndarray: z-axis direction vector (3,)
    """
    w, x, y, z = q[0], q[1], q[2], q[3]
    z_axis = np.array([
        2 * (x * z + w * y),
        2 * (y * z - w * x),
        1 - 2 * (x**2 + y**2)
    ])
    return z_axis / np.linalg.norm(z_axis)


def generate_hall_data_from_dipole(sensor_ids, p_sensor_array, R_sensor_array, d_list, source_p_Ci, m_Ci, R_CORR, noise_level=1e-10):
    """
    Generate synthetic Hall sensor data using mag_dipole_model.

    The magnetic field at each sensor is computed as the dipole field
    generated by a source at p_Ci, evaluated at each sensor position.

    Args:
        sensor_ids: list of active sensor IDs (1-12)
        p_sensor_array: 3D position of sensor array center (global frame)
        R_sensor_array: 3x3 rotation matrix of sensor array orientation
        d_list: 12x3 array of sensor positions relative to array center
        source_p_Ci: 3D position of the magnetic dipole source
        m_Ci: 3D magnetic moment vector of the source (direction already included)
        R_CORR: dict of rotation correction matrices per sensor group
        noise_level: standard deviation of Gaussian noise to add

    Returns:
        list of MockSensorReading
    """
    from localization_service_node import get_sensor_group, GS_TO_TESLA

    data = []
    for sid in sensor_ids:
        sensor_idx = sid - 1  # 0-indexed

        # Sensor position in global frame: p_s = p_array + R @ d_j
        d_j = d_list[sensor_idx]
        p_sensor_global = p_sensor_array + R_sensor_array @ d_j

        # Compute magnetic field at sensor using dipole model (in global frame, Tesla)
        b_global, _ = mag_dipole_model(p_sensor_global, m_Ci, source_p_Ci)

        # Transform from global to sensor array frame: b_array = R.T @ b_global
        b_array = R_sensor_array.T @ b_global

        # Apply R_CORR.T to get raw sensor measurement (sensor local frame)
        # R_CORR transforms sensor local -> array frame, so R_CORR.T is array -> sensor local
        group = get_sensor_group(sid)
        if group is not None and group in R_CORR:
            b_sensor = R_CORR[group].T @ b_array
        else:
            b_sensor = b_array

        # Convert from Tesla to Gs (Hall sensor output is in Gs)
        # B_meas = b_corrected * GS_TO_TESLA, so b_corrected = B_meas / GS_TO_TESLA
        b_sensor_gs = b_sensor / GS_TO_TESLA

        # Add noise (in Gs)
        x = b_sensor_gs[0] + noise_level * np.random.randn()
        y = b_sensor_gs[1] + noise_level * np.random.randn()
        z = b_sensor_gs[2] + noise_level * np.random.randn()

        data.append(MockSensorReading(id=sid, x=x, y=y, z=z))

    return data


# Legacy function for backwards compatibility (random data)
def generate_synthetic_hall_data(sensor_ids, noise_level=1e-10):
    """
    Generate synthetic Hall sensor data for testing (random baseline).

    Args:
        sensor_ids: list of active sensor IDs
        noise_level: standard deviation of Gaussian noise

    Returns:
        list of MockSensorReading
    """
    data = []
    for sid in sensor_ids:
        # Generate realistic-looking magnetic field values with noise
        x = (np.random.random() - 0.5) * 1e-9 + noise_level * np.random.randn()
        y = (np.random.random() - 0.5) * 1e-9 + noise_level * np.random.randn()
        z = (np.random.random() - 0.5) * 1e-9 + noise_level * np.random.randn()
        data.append(MockSensorReading(id=sid, x=x, y=y, z=z))
    return data


def create_cci_test_request(cycle_id=1):
    """
    Create a CCI mode test request (3 slots, no background).
    Uses mag_dipole_model to generate synthetic Hall sensor readings.

    Slot mapping:
        slot 0 -> diana7
        slot 1 -> arm1
        slot 2 -> arm2
    """
    # Load configuration to get R_CORR
    load_configuration()
    # Re-import to get the updated R_CORR after load_configuration()
    import localization_service_node
    global R_CORR
    R_CORR = localization_service_node.R_CORR

    # sensor_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    sensor_ids = [2, 8, 9]

    # Ground truth pose of the sensor array
    gt_pose = MockPose(
        x=0.09077731745391011,
        y=0.24106503799018728,
        z=0.2216948888742314,
        qx=0.006230713847804758,
        qy=0.012267896314745962,
        qz=-0.013909541307199203,
        qw=0.9998085824724553
    )
    p_sensor_array = np.array([gt_pose.position.x, gt_pose.position.y, gt_pose.position.z])
    R_sensor_array = quaternion_to_rotation_matrix([gt_pose.orientation.w, gt_pose.orientation.x, gt_pose.orientation.y, gt_pose.orientation.z])

    # Sensor positions relative to array center (from localization_service_node.py d_list)
    d = 2e-3  # 2mm offset scale
    de1, de2, de3 = 1.0e-3, 2.0e-3, 2.1e-3
    d_list = np.array([
        [-de2/2,  de3/2, -de1], [-de2/2,  de3/2,  0   ], [-de2/2,  de3/2,  de1 ],
        [-de2/2, -de3/2, -de1], [-de2/2, -de3/2,  0   ], [-de2/2, -de3/2,  de1 ],
        [ de2/2,  de3/2, -de1], [ de2/2,  de3/2,  0   ], [ de2/2,  de3/2,  de1 ],
        [ de2/2, -de3/2, -de1], [ de2/2, -de3/2,  0   ], [ de2/2, -de3/2,  de1 ],
    ])

    # Magnetic source configurations from cycle_0000.json
    # Slot 0: diana7
    p_Ci_0 = np.array([0.11430518080049068, -0.029413607180472767, 0.40804045224164875])
    q_0 = np.array([0.31509559856329966, -0.9467646103007277, 0.06324273115211115, -0.01875882204640797])  # w, x, y, z
    z_axis_0 = quaternion_z_axis(q_0)
    moment_magnitude = 1  # A*m^2 (arbitrary scale)
    m_Ci_0 = moment_magnitude * z_axis_0

    # Slot 1: arm1
    p_Ci_1 = np.array([-0.08160478580088681, 0.3430849524344143, 0.3700606824601058])
    q_1 = np.array([0.1778105633874994, -0.2296816382573243, 0.9061897134359064, -0.30732710888921216])
    z_axis_1 = quaternion_z_axis(q_1)
    m_Ci_1 = moment_magnitude * z_axis_1

    # Slot 2: arm2
    p_Ci_2 = np.array([0.34130888888978345, 0.34695421617815314, 0.37371570742432847])
    q_2 = np.array([-0.22643870874670013, 0.2962766990317989, 0.845468976453598, -0.38226671140246216])
    z_axis_2 = quaternion_z_axis(q_2)
    m_Ci_2 = moment_magnitude * z_axis_2

    sources = [
        {'p_Ci': p_Ci_0, 'm_Ci': m_Ci_0, 'name': 'diana7'},
        {'p_Ci': p_Ci_1, 'm_Ci': m_Ci_1, 'name': 'arm1'},
        {'p_Ci': p_Ci_2, 'm_Ci': m_Ci_2, 'name': 'arm2'},
    ]

    # Pose for slot 0 (diana7) - TCP pose of EM coil
    pose0 = MockPose(x=p_Ci_0[0], y=p_Ci_0[1], z=p_Ci_0[2], qx=q_0[1], qy=q_0[2], qz=q_0[3], qw=q_0[0])

    # Pose for slot 1 (arm1)
    pose1 = MockPose(x=p_Ci_1[0], y=p_Ci_1[1], z=p_Ci_1[2], qx=q_1[1], qy=q_1[2], qz=q_1[3], qw=q_1[0])

    # Pose for slot 2 (arm2)
    pose2 = MockPose(x=p_Ci_2[0], y=p_Ci_2[1], z=p_Ci_2[2], qx=q_2[1], qy=q_2[2], qz=q_2[3], qw=q_2[0])

    # Generate sensor data using dipole model
    slot0_data = generate_hall_data_from_dipole(
        sensor_ids, p_sensor_array, R_sensor_array, d_list,
        sources[0]['p_Ci'], sources[0]['m_Ci'], R_CORR
    )
    slot1_data = generate_hall_data_from_dipole(
        sensor_ids, p_sensor_array, R_sensor_array, d_list,
        sources[1]['p_Ci'], sources[1]['m_Ci'], R_CORR
    )
    slot2_data = generate_hall_data_from_dipole(
        sensor_ids, p_sensor_array, R_sensor_array, d_list,
        sources[2]['p_Ci'], sources[2]['m_Ci'], R_CORR
    )

    slot_data = [
        MockSlotData(slot=0, sensor_data=slot0_data, pose=pose0),
        MockSlotData(slot=1, sensor_data=slot1_data, pose=pose1),
        MockSlotData(slot=2, sensor_data=slot2_data, pose=pose2),
    ]

    return MockLocalizeCycleRequest(
        cycle_id=cycle_id,
        mode='CCI',
        sensor_ids=sensor_ids,
        slot_data=slot_data,
        ground_truth_pose=gt_pose,
    )


def create_cvt_test_request(cycle_id=1):
    """
    Create a CVT mode test request (4 slots, with background subtraction).
    Uses mag_dipole_model to generate synthetic Hall sensor readings.

    Slot mapping:
        slot 0 -> diana7 (B1 - B0)
        slot 1 -> arm1 (B2 - B0)
        slot 2 -> arm2 (B3 - B0)
        slot 3 -> B0 (background, no pose)
    """
    # Load configuration to get R_CORR
    load_configuration()
    # Re-import to get the updated R_CORR after load_configuration()
    import localization_service_node
    global R_CORR
    R_CORR = localization_service_node.R_CORR

    sensor_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

    # Ground truth pose of the sensor array
    gt_pose = MockPose(
        x=0.09077731745391011,
        y=0.24106503799018728,
        z=0.2216948888742314,
        qx=0.006230713847804758,
        qy=0.012267896314745962,
        qz=-0.013909541307199203,
        qw=0.9998085824724553
    )
    p_sensor_array = np.array([gt_pose.position.x, gt_pose.position.y, gt_pose.position.z])
    R_sensor_array = quaternion_to_rotation_matrix([gt_pose.orientation.w, gt_pose.orientation.x, gt_pose.orientation.y, gt_pose.orientation.z])

    # Sensor positions relative to array center
    de1, de2, de3 = 1.0e-3, 2.0e-3, 2.1e-3
    d_list = np.array([
        [-de2/2,  de3/2, -de1], [-de2/2,  de3/2,  0   ], [-de2/2,  de3/2,  de1 ],
        [-de2/2, -de3/2, -de1], [-de2/2, -de3/2,  0   ], [-de2/2, -de3/2,  de1 ],
        [ de2/2,  de3/2, -de1], [ de2/2,  de3/2,  0   ], [ de2/2,  de3/2,  de1 ],
        [ de2/2, -de3/2, -de1], [ de2/2, -de3/2,  0   ], [ de2/2, -de3/2,  de1 ],
    ])

    # Magnetic source configurations from cycle_0000.json
    p_Ci_0 = np.array([0.11430518080049068, -0.029413607180472767, 0.40804045224164875])
    q_0 = np.array([0.31509559856329966, -0.9467646103007277, 0.06324273115211115, -0.01875882204640797])
    z_axis_0 = quaternion_z_axis(q_0)

    p_Ci_1 = np.array([-0.08160478580088681, 0.3430849524344143, 0.3700606824601058])
    q_1 = np.array([0.1778105633874994, -0.2296816382573243, 0.9061897134359064, -0.30732710888921216])
    z_axis_1 = quaternion_z_axis(q_1)

    p_Ci_2 = np.array([0.34130888888978345, 0.34695421617815314, 0.37371570742432847])
    q_2 = np.array([-0.22643870874670013, 0.2962766990317989, 0.845468976453598, -0.38226671140246216])
    z_axis_2 = quaternion_z_axis(q_2)

    moment_magnitude = 1  # A*m^2

    sources = [
        {'p_Ci': p_Ci_0, 'm_Ci': moment_magnitude * z_axis_0, 'name': 'diana7'},
        {'p_Ci': p_Ci_1, 'm_Ci': moment_magnitude * z_axis_1, 'name': 'arm1'},
        {'p_Ci': p_Ci_2, 'm_Ci': moment_magnitude * z_axis_2, 'name': 'arm2'},
    ]

    # B0 (slot 3) - background only (no EM coil active, just ambient noise)
    b0_data = generate_hall_data_from_dipole(
        sensor_ids, p_sensor_array, R_sensor_array, d_list,
        np.array([0.0, 0.0, 0.0]),  # No source, just noise
        np.array([0.0, 0.0, 0.0]),  # Zero moment = no field contribution
        R_CORR
    )

    # Slot 0 (diana7) - signal with background (CVT subtracts B0)
    pose0 = MockPose(x=p_Ci_0[0], y=p_Ci_0[1], z=p_Ci_0[2], qx=q_0[1], qy=q_0[2], qz=q_0[3], qw=q_0[0])
    slot0_data = generate_hall_data_from_dipole(
        sensor_ids, p_sensor_array, R_sensor_array, d_list,
        sources[0]['p_Ci'], sources[0]['m_Ci'], R_CORR
    )

    # Slot 1 (arm1) - signal with background
    pose1 = MockPose(x=p_Ci_1[0], y=p_Ci_1[1], z=p_Ci_1[2], qx=q_1[1], qy=q_1[2], qz=q_1[3], qw=q_1[0])
    slot1_data = generate_hall_data_from_dipole(
        sensor_ids, p_sensor_array, R_sensor_array, d_list,
        sources[1]['p_Ci'], sources[1]['m_Ci'], R_CORR
    )

    # Slot 2 (arm2) - signal with background
    pose2 = MockPose(x=p_Ci_2[0], y=p_Ci_2[1], z=p_Ci_2[2], qx=q_2[1], qy=q_2[2], qz=q_2[3], qw=q_2[0])
    slot2_data = generate_hall_data_from_dipole(
        sensor_ids, p_sensor_array, R_sensor_array, d_list,
        sources[2]['p_Ci'], sources[2]['m_Ci'], R_CORR
    )

    slot_data = [
        MockSlotData(slot=0, sensor_data=slot0_data, pose=pose0),
        MockSlotData(slot=1, sensor_data=slot1_data, pose=pose1),
        MockSlotData(slot=2, sensor_data=slot2_data, pose=pose2),
        MockSlotData(slot=3, sensor_data=b0_data, pose=MockPose()),  # No pose for B0
    ]

    return MockLocalizeCycleRequest(
        cycle_id=cycle_id,
        mode='CVT',
        sensor_ids=sensor_ids,
        slot_data=slot_data,
        ground_truth_pose=gt_pose,
    )


def test_individual_functions():
    """Test individual processing functions."""
    print("\n--- Testing Individual Functions ---\n")

    # Test quaternion_z_axis
    print("1. quaternion_z_axis:")
    q_identity = np.array([1, 0, 0, 0])  # Identity quaternion
    z = quaternion_z_axis(q_identity)
    print(f"   Identity quaternion z-axis: {z}")

    q_rotated = np.array([0.995, 0, 0, 0.1])  # ~11.5 deg rotation around z
    z_rot = quaternion_z_axis(q_rotated)
    print(f"   Rotated quaternion z-axis: {z_rot}")

    # Test process_hall_data
    print("\n2. process_hall_data:")
    sensor_ids = [1, 2, 3]
    readings = [
        MockSensorReading(id=1, x=1e-9, y=2e-9, z=3e-9),
        MockSensorReading(id=2, x=4e-9, y=5e-9, z=6e-9),
        MockSensorReading(id=3, x=7e-9, y=8e-9, z=9e-9),
    ]
    B = process_hall_data(readings)
    print(f"   Input: 3 sensors")
    print(f"   Output shape: {B.shape}")
    print(f"   Output:\n{B}")

    # Test build_D_cal
    print("\n3. build_D_cal:")
    sensor_ids = [1, 4, 7, 10]  # One from each group
    D = build_D_cal(sensor_ids)
    print(f"   Input sensors: {sensor_ids}")
    print(f"   Output shape: {D.shape}")
    print(f"   Output:\n{D}")

    print("\n--- Individual Function Tests Complete ---\n")


def compute_orientation_error(R_est, R_true):
    """
    Compute orientation error between estimated and true rotation matrices.

    Args:
        R_est: Estimated rotation matrix (3x3)
        R_true: True rotation matrix (3x3)

    Returns:
        float: Orientation error in degrees
    """
    # Compute the difference rotation matrix
    R_diff = R_est @ R_true.T

    # Extract the rotation angle from the difference matrix
    # norm(R_diff - I, 'fro') = 2*sqrt(2)*sin(theta/2) for small theta
    # So theta = 2*arcsin(norm(R_diff - I, 'fro') / (2*sqrt(2)))
    frobenius_norm = np.sqrt(np.sum((R_diff - np.eye(3))**2))
    theta_rad = 2 * np.arcsin(frobenius_norm / (2 * np.sqrt(2)))
    theta_deg = np.rad2deg(theta_rad)

    return theta_deg


def test_standalone():
    """Test the localization pipeline without ROS."""
    print("=" * 60)
    print("Testing GELS Localization Service (Standalone)")
    print("=" * 60)

    # Load configuration
    load_configuration()

    # Ground truth pose (from cycle_0000.json)
    gt_position = np.array([0.09077731745391011, 0.24106503799018728, 0.2216948888742314])
    gt_quaternion = np.array([0.9998085824724553, 0.006230713847804758,
                              0.012267896314745962, -0.013909541307199203])  # [w, x, y, z]
    R_true = quaternion_to_rotation_matrix(gt_quaternion)

    print("\nGround Truth:")
    print(f"  Position: ({gt_position[0]:.6f}, {gt_position[1]:.6f}, {gt_position[2]:.6f})")
    print(f"  Quaternion: ({gt_quaternion[0]:.6f}, {gt_quaternion[1]:.6f}, {gt_quaternion[2]:.6f}, {gt_quaternion[3]:.6f})")

    # Test CCI mode
    print("\n--- Testing CCI Mode ---")
    req_cci = create_cci_test_request(cycle_id=100)
    print(f"Request: cycle_id={req_cci.cycle_id}, mode={req_cci.mode}")
    print(f"Sensors: {req_cci.sensor_ids}")
    print(f"Slots: {[s.slot for s in req_cci.slot_data]}")

    resp_cci = handle_localize_cycle(req_cci)
    print(f"\nResult: success={resp_cci.success}")
    if resp_cci.success:
        p = resp_cci.localization_pose.position
        q = resp_cci.localization_pose.orientation

        print(f"Estimated Position: ({p.x:.6f}, {p.y:.6f}, {p.z:.6f})")
        print(f"Estimated Orientation: ({q.x:.4f}, {q.y:.4f}, {q.z:.4f}, {q.w:.4f})")
        print(f"Position Error (norm): {resp_cci.position_error:.6f} m")
        print(f"Orientation Error: {np.rad2deg(resp_cci.orientation_error):.4f} deg")
    else:
        print("Localization failed!")

    # Test CVT mode
    print("\n--- Testing CVT Mode ---")
    req_cvt = create_cvt_test_request(cycle_id=101)
    print(f"Request: cycle_id={req_cvt.cycle_id}, mode={req_cvt.mode}")
    print(f"Sensors: {req_cvt.sensor_ids}")
    print(f"Slots: {[s.slot for s in req_cvt.slot_data]}")

    resp_cvt = handle_localize_cycle(req_cvt)
    print(f"\nResult: success={resp_cvt.success}")
    if resp_cvt.success:
        p = resp_cvt.localization_pose.position
        q = resp_cvt.localization_pose.orientation

        print(f"Estimated Position: ({p.x:.6f}, {p.y:.6f}, {p.z:.6f})")
        print(f"Estimated Orientation: ({q.x:.4f}, {q.y:.4f}, {q.z:.4f}, {q.w:.4f})")
        print(f"Position Error (norm): {resp_cvt.position_error:.6f} m")
        print(f"Orientation Error: {np.rad2deg(resp_cvt.orientation_error):.4f} deg")
    else:
        print("Localization failed!")

    print("\n" + "=" * 60)
    print("Test Complete")
    print("=" * 60)


if __name__ == '__main__':
    print("GELS Localization Service Test")
    print("=" * 60)

    # First test individual functions
    # test_individual_functions()

    # Then test the full pipeline
    test_standalone()
